### ISSUE TITLE
A Wire.endTransmission after Wire.requestFrom is not valid.

### ISSUE THREAD

**Issue by Koepel** [zrecore/freeIMU#8]
In the file bma180.cpp in the functions readAccel, getRegValue and getIDs, there is a Wire.endTransmission after a Wire.requestFrom. That Wire.endTransmission can be removed, it should only be used when writing data. Since the return value of those Wire.endTransmission are used, it is not defined what the return value will be.

**Comment by zrecore** [comment]
Please see https://github.com/mjs513/FreeIMU-Updates instead of this copy of FreeIMU

**Comment by Koepel** [comment]
I'm sorry, I didn't know that.
